const express = require("express");
const { getRouter } = require("stremio-addon-sdk");
const addonInterface = require("./addon");
const { createAddonInterface } = require("./addon");
const path = require("path");
const qs = require("querystring");

const app = express();
const port = process.env.PORT || 7000;
const configuredAddons = new Map();

app.use((req, res, next) => {
    const requestedHeaders = req.get("Access-Control-Request-Headers");

    res.setHeader("Access-Control-Allow-Origin", "*");
    res.setHeader("Access-Control-Allow-Methods", "GET, OPTIONS");
    res.setHeader("Access-Control-Allow-Headers", requestedHeaders || "Content-Type, Accept, Origin, Range, Stremio-Addon");
    res.setHeader("Access-Control-Allow-Private-Network", "true");
    res.setHeader("Cross-Origin-Resource-Policy", "cross-origin");

    if (req.method === "OPTIONS") {
        res.status(204).end();
        return;
    }

    next();
});

function decodeBase64Url(value) {
    const normalized = value.replace(/-/g, "+").replace(/_/g, "/");
    const padded = normalized + "=".repeat((4 - normalized.length % 4) % 4);
    return Buffer.from(padded, "base64").toString("utf8");
}

function getConfiguredAddon(encodedConfig) {
    if (configuredAddons.has(encodedConfig)) {
        return configuredAddons.get(encodedConfig);
    }

    let config = {};
    try {
        config = JSON.parse(decodeBase64Url(encodedConfig));
    } catch {
        config = {};
    }

    const addon = createAddonInterface({
        tmdbKey: typeof config.tmdbKey === "string" ? config.tmdbKey.trim() : "",
        tmdbAccessToken: typeof config.tmdbAccessToken === "string" ? config.tmdbAccessToken.trim() : ""
    });
    configuredAddons.set(encodedConfig, addon);
    return addon;
}

function sendJson(res, payload) {
    res.setHeader("Content-Type", "application/json; charset=utf-8");
    res.end(JSON.stringify(payload));
}

async function handleConfiguredResource(req, res, next) {
    const [encodedConfig, resource, type, id, extraParam] = Object.values(req.params);
    const extra = extraParam ? qs.parse(extraParam) : {};
    const addon = getConfiguredAddon(encodedConfig);

    try {
        const response = await addon.get(resource, type, id, extra);
        sendJson(res, response);
    } catch (error) {
        if (error.noHandler && next) {
            next();
            return;
        }
        console.error(error);
        res.statusCode = 500;
        sendJson(res, { err: "handler error" });
    }
}

// Serve static files (like bg.jpg) from the current directory
app.use(express.static(path.join(__dirname)));

// Configured Stremio addon URLs. The encoded config is generated by index.html.
app.get(["/configure", "/configure/:config/configure"], (req, res) => {
    res.sendFile(path.join(__dirname, "index.html"));
});

app.get("/configure/:config/manifest.json", (req, res) => {
    const addon = getConfiguredAddon(req.params.config);
    sendJson(res, addon.manifest);
});

app.get(
    /^\/configure\/([^/]+)\/([^/]+)\/([^/]+)\/([^/]+)(?:\/([^/]+))?\.json$/,
    handleConfiguredResource
);

// Use the Stremio Addon SDK router
app.use("/", getRouter(addonInterface));

// Landing page for the root URL
app.get("/", (req, res) => {
    res.sendFile(path.join(__dirname, "index.html"));
});

app.listen(port, () => {
    console.log(`Addon active on port ${port}`);
    console.log(`http://127.0.0.1:${port}/manifest.json`);
});
